# Generated by Django 3.2 on 2021-04-07 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_hash', models.CharField(max_length=256)),
                ('pdb', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('remember_me', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_created_at', models.DateTimeField()),
                ('user_updated_at', models.DateTimeField()),
                ('reset_password_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MorphRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_a_name', models.CharField(max_length=512)),
                ('protein_b_name', models.CharField(max_length=512)),
                ('protein_a', models.TextField()),
                ('protein_b', models.TextField()),
                ('morping_count', models.IntegerField()),
                ('morph_request_created_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphserverapp.user')),
            ],
        ),
    ]
