# Generated by Django 3.2 on 2021-04-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphserverapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remember_me',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
    ]
