# Generated by Django 3.2 on 2021-04-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphserverapp', '0002_auto_20210411_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morphrequest',
            old_name='morph_request_created_at',
            new_name='created_at',
        ),
    ]
