# Generated by Django 3.2 on 2021-04-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphserverapp', '0003_rename_morph_request_created_at_morphrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphrequest',
            name='auto_interpolation',
            field=models.BooleanField(default=False),
        ),
    ]
