# Generated by Django 3.2 on 2021-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphserverapp', '0004_morphrequest_auto_interpolation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdb',
            old_name='pdb_hash',
            new_name='pdb_name',
        ),
        migrations.RemoveField(
            model_name='morphrequest',
            name='protein_a',
        ),
        migrations.RemoveField(
            model_name='morphrequest',
            name='protein_b',
        ),
        migrations.RemoveField(
            model_name='pdb',
            name='pdb',
        ),
        migrations.AddField(
            model_name='pdb',
            name='pdb_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='morphrequest',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='morphrequest',
            name='protein_a_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='morphrequest',
            name='protein_b_name',
            field=models.CharField(max_length=256),
        ),
    ]
