# Generated by Django 3.2 on 2021-04-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphserverapp', '0013_alter_pdb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
